export const SHOW_APP_LOADING = 'SHOW_APP_LOADING';
export const HIDE_APP_LOADING = 'HIDE_APP_LOADING';
export const NO_BET_CONTENT_TOAST = 'NO_BET_CONTENT_TOAST';
export const NO_BET_MONEY_TOAST = 'NO_BET_MONEY_TOAST';
